from core.agents.base_prompts import USER_SCOPE_EXTRACTION_PROMPT, global_scope_extraction_prompt

SOLUTION_AGENT_USER_SCOPE_PROMPT = USER_SCOPE_EXTRACTION_PROMPT
SOLUTION_AGENT_GLOBAL_SCOPE_PROMPT = global_scope_extraction_prompt("solution")
